ALTER TABLE "Photo"
ALTER COLUMN "fileSize" TYPE DOUBLE PRECISION
USING "fileSize"::DOUBLE PRECISION;

ALTER TABLE "GalleryUploadItem"
ALTER COLUMN "fileSize" TYPE DOUBLE PRECISION
USING "fileSize"::DOUBLE PRECISION,
ADD COLUMN "multipartUploadId" TEXT,
ADD COLUMN "multipartPartSize" INTEGER,
ADD COLUMN "multipartPartCount" INTEGER;
