import { Banknote, Landmark, Plus, WalletCards } from "lucide-react";
import { FormSubmitButton } from "@/components/form-submit-button";
import { formatInvoiceMoney } from "@/lib/customer-invoices";
import { recordGeneratedInvoicePaymentAction } from "@/lib/generated-invoice-actions";

const methodLabels: Record<string, string> = { bank_transfer: "Banki átutalás", cash: "Készpénz", card: "Bankkártya", other: "Egyéb" };

export function GeneratedInvoicePaymentPanel({ invoiceId, totalCents, paidCents, status, currency, payments }: { invoiceId: string; totalCents: number; paidCents: number; status: string; currency: string; payments: Array<{ id: string; amountCents: number; paidAt: Date; method: string; note: string | null }> }) {
  const outstanding = Math.max(0, totalCents - paidCents);
  const record = recordGeneratedInvoicePaymentAction.bind(null, invoiceId);
  const today = new Date().toISOString().slice(0, 10);
  return <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft sm:p-6"><header className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.14em] text-graphite/55">Fizetések</p><h2 className="mt-1 text-xl font-semibold">Fizetési állapot</h2></div><WalletCards size={22} className="text-brass"/></header><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-md bg-paper p-4"><span className="text-xs uppercase tracking-[0.1em] text-graphite/55">Számla összege</span><strong className="mt-2 block text-lg">{formatInvoiceMoney(totalCents, currency)}</strong></div><div className="rounded-md bg-emerald-50 p-4"><span className="text-xs uppercase tracking-[0.1em] text-emerald-700/70">Beérkezett</span><strong className="mt-2 block text-lg text-emerald-800">{formatInvoiceMoney(paidCents, currency)}</strong></div><div className={`rounded-md p-4 ${outstanding ? "bg-red-50" : "bg-emerald-50"}`}><span className="text-xs uppercase tracking-[0.1em] text-graphite/55">Nyitott összeg</span><strong className="mt-2 block text-lg">{formatInvoiceMoney(outstanding, currency)}</strong></div></div>
    {! ["draft", "cancelled"].includes(status) && outstanding > 0 ? <form action={record} className="mt-5 grid gap-3 rounded-md border border-ink/10 bg-paper p-4 lg:grid-cols-[1fr_1fr_1fr_1.3fr_auto]"><label className="space-y-1"><span className="text-xs font-medium text-graphite/70">Összeg</span><input name="amount" required inputMode="decimal" defaultValue={(outstanding / 100).toFixed(2).replace(".", ",")} className="h-10 w-full rounded-md border border-ink/15 px-3 text-sm"/></label><label className="space-y-1"><span className="text-xs font-medium text-graphite/70">Dátum</span><input name="paidAt" required type="date" defaultValue={today} className="h-10 w-full rounded-md border border-ink/15 px-3 text-sm"/></label><label className="space-y-1"><span className="text-xs font-medium text-graphite/70">Mód</span><select name="method" className="h-10 w-full rounded-md border border-ink/15 bg-white px-3 text-sm"><option value="bank_transfer">Banki átutalás</option><option value="cash">Készpénz</option><option value="card">Bankkártya</option><option value="other">Egyéb</option></select></label><label className="space-y-1"><span className="text-xs font-medium text-graphite/70">Megjegyzés</span><input name="note" className="h-10 w-full rounded-md border border-ink/15 px-3 text-sm"/></label><FormSubmitButton className="mt-auto h-10" pendingLabel="Mentés…"><Plus size={16}/> Rögzítés</FormSubmitButton></form> : null}
    <div className="mt-5 space-y-2">{payments.length ? payments.map((payment) => <article key={payment.id} className="flex items-center gap-3 rounded-md border border-ink/10 p-3"><span className="flex size-9 items-center justify-center rounded-full bg-paper">{payment.method === "cash" ? <Banknote size={17}/> : <Landmark size={17}/>}</span><div className="flex-1"><strong className="text-sm">{methodLabels[payment.method] ?? payment.method}</strong><p className="text-xs text-graphite/60">{payment.paidAt.toLocaleDateString("hu-HU", { timeZone: "UTC" })}{payment.note ? ` · ${payment.note}` : ""}</p></div><strong>{formatInvoiceMoney(payment.amountCents, currency)}</strong></article>) : <p className="rounded-md bg-paper p-4 text-sm text-graphite/65">Még nincs rögzített befizetés.</p>}</div>
  </section>;
}
