"use client";

import Link from "next/link";
import { CheckCircle2, Download, ExternalLink, FileCheck2, FilePenLine, MoreHorizontal, PencilLine, ReceiptText, RotateCcw, Undo2, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cancelGeneratedInvoiceAction, createCorrectionInvoiceDraftAction, finalizeGeneratedInvoiceAction, setGeneratedInvoicePaidAction } from "@/lib/generated-invoice-actions";

export function GeneratedInvoiceRowMenu({ invoice }: { invoice: { id: string; number: string; status: string; documentType: string; publicToken: string | null; generated: boolean } }) {
  const [open, setOpen] = useState(false);
  const [dialog, setDialog] = useState<"finalize" | "cancel" | null>(null);
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const outside = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); };
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); setDialog(null); } };
    document.addEventListener("mousedown", outside); document.addEventListener("keydown", escape);
    return () => { document.removeEventListener("mousedown", outside); document.removeEventListener("keydown", escape); };
  }, []);
  const finalize = finalizeGeneratedInvoiceAction.bind(null, invoice.id);
  const cancel = cancelGeneratedInvoiceAction.bind(null, invoice.id);
  const paid = setGeneratedInvoicePaidAction.bind(null, invoice.id, true);
  const unpaid = setGeneratedInvoicePaidAction.bind(null, invoice.id, false);
  const correction = createCorrectionInvoiceDraftAction.bind(null, invoice.id);
  return <div className="relative" ref={root}><button type="button" aria-label={`${invoice.number} műveletei`} aria-expanded={open} onClick={() => setOpen((current) => !current)} className="flex size-10 items-center justify-center rounded-md hover:bg-ink/5"><MoreHorizontal size={20}/></button>
    {open ? <div role="menu" className="absolute right-0 top-11 z-30 w-60 rounded-md border border-ink/10 bg-white p-1 shadow-xl"><Link href={`/admin/invoices/${invoice.id}`} className="flex items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><ReceiptText size={16}/> Megnyitás</Link>{invoice.generated && invoice.status === "draft" ? <><Link href={`/admin/invoices/${invoice.id}/edit`} className="flex items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><PencilLine size={16}/> Szerkesztés</Link><button type="button" onClick={() => { setOpen(false); setDialog("finalize"); }} className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><FileCheck2 size={16}/> Véglegesítés</button></> : null}{invoice.generated && invoice.status !== "draft" ? <a href={`/api/admin/invoices/${invoice.id}/pdf`} className="flex items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><Download size={16}/> PDF letöltése</a> : null}{invoice.publicToken ? <Link target="_blank" href={`/rechnung/${invoice.publicToken}`} className="flex items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><ExternalLink size={16}/> Ügyfélnézet</Link> : null}{invoice.generated && invoice.documentType !== "cancellation" && ["final", "sent", "partial"].includes(invoice.status) ? <form action={paid}><input type="hidden" name="returnTo" value="/admin/invoices"/><button className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><CheckCircle2 size={16}/> Megjelölés fizetettként</button></form> : null}{invoice.generated && invoice.documentType !== "cancellation" && ["partial", "paid"].includes(invoice.status) ? <form action={unpaid}><input type="hidden" name="returnTo" value="/admin/invoices"/><button className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><Undo2 size={16}/> Fizetések visszaállítása</button></form> : null}{invoice.generated && invoice.status === "cancelled" && invoice.documentType !== "cancellation" ? <form action={correction}><button className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm hover:bg-paper"><FilePenLine size={16}/> Helyesbítő piszkozat</button></form> : null}{invoice.generated && invoice.documentType !== "cancellation" && ["final", "sent", "partial", "paid"].includes(invoice.status) ? <><div className="my-1 border-t border-ink/10"/><button type="button" onClick={() => { setOpen(false); setDialog("cancel"); }} className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-red-700 hover:bg-red-50"><RotateCcw size={16}/> Sztornózás</button></> : null}</div> : null}
    {dialog ? <div className="fixed inset-0 z-50 grid place-items-center bg-ink/50 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setDialog(null); }}><section role="dialog" aria-modal="true" className="relative w-full max-w-lg rounded-lg bg-white p-6 shadow-2xl"><button type="button" onClick={() => setDialog(null)} aria-label="Bezárás" className="absolute right-4 top-4 flex size-9 items-center justify-center rounded-md hover:bg-paper"><X size={18}/></button><p className="text-xs font-semibold uppercase tracking-[0.16em] text-brass">{dialog === "finalize" ? "Számla véglegesítése" : "Számla sztornózása"}</p><h2 className="mt-3 text-2xl font-semibold">{dialog === "finalize" ? "Véglegesíted a számlát?" : "Biztosan sztornózod?"}</h2><p className="mt-3 text-sm leading-6 text-graphite/70">{dialog === "finalize" ? "Véglegesítés után a tartalom és a hivatalos sorszám már nem módosítható." : "Az eredeti számla megmarad, és külön sorszámú negatív sztornóbizonylat készül."}</p><div className="mt-4 rounded-md bg-paper p-3 font-semibold">{invoice.number}</div>{dialog === "finalize" ? <form action={finalize} className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setDialog(null)} className="h-11 rounded-md border border-ink/15 px-4 text-sm font-medium">Mégse</button><button className="h-11 rounded-md bg-ink px-4 text-sm font-medium text-white">Véglegesítem</button></form> : <form action={cancel} className="mt-5"><label className="space-y-2"><span className="text-sm font-medium">Sztornózás oka (opcionális)</span><textarea name="reason" rows={3} className="w-full rounded-md border border-ink/15 p-3 text-sm"/></label><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setDialog(null)} className="h-11 rounded-md border border-ink/15 px-4 text-sm font-medium">Mégse</button><button className="h-11 rounded-md bg-red-700 px-4 text-sm font-medium text-white">Sztornózom</button></div></form>}</section></div> : null}
  </div>;
}
